version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - appnet
    platform: "linux/amd64"


  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: qt_server
    depends_on:
      - db
    networks:
      - appnet
    platform: "linux/amd64"

networks:
  appnet:
