FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    qt5-default qtbase5-dev qmake build-essential curl && \
    apt-get clean

# Копируем проект внутрь контейнера
WORKDIR /app
COPY ../server ./server
COPY entrypoint.sh .

# Даем права на запуск скрипта
RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
