FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    qtbase5-dev qtchooser qt5-qmake build-essential curl \
    libpq-dev \
    libqt5sql5-psql && \
    apt-get clean


# Копируем проект внутрь контейнера
WORKDIR /app/Server
COPY . .

# Копируем скрипт запуска
WORKDIR /app
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
