import QtQuick 2.0
import Sailfish.Silica 1.0

Item {
    property alias country: combobox_country.value
    Column {
        Text {
            id: lbl
            text: "Country"
        }
        ComboBox {
            id: combobox_country
            width: 300
            value: ""
            menu: ContextMenu {
                MenuItem { text: "AF - Afghanistan"; onClicked: combobox_country.value = text }
                MenuItem { text: "AL - Albania"; onClicked: combobox_country.value = text }
                MenuItem { text: "DZ - Algeria"; onClicked: combobox_country.value = text }
                MenuItem { text: "AS - American Samoa"; onClicked: combobox_country.value = text }
                MenuItem { text: "AD - Andorra"; onClicked: combobox_country.value = text }
                MenuItem { text: "AO - Angola"; onClicked: combobox_country.value = text }
                MenuItem { text: "AI - Anguilla"; onClicked: combobox_country.value = text }
                MenuItem { text: "AQ - Antarctica"; onClicked: combobox_country.value = text }
                MenuItem { text: "AR - Argentina"; onClicked: combobox_country.value = text }
                MenuItem { text: "AM - Armenia"; onClicked: combobox_country.value = text }
                MenuItem { text: "AW - Aruba"; onClicked: combobox_country.value = text }
                MenuItem { text: "AU - Australia"; onClicked: combobox_country.value = text }
                MenuItem { text: "AT - Austria"; onClicked: combobox_country.value = text }
                MenuItem { text: "AZ - Azerbaijan"; onClicked: combobox_country.value = text }
                MenuItem { text: "BS - Bahamas"; onClicked: combobox_country.value = text }
                MenuItem { text: "BH - Bahrain"; onClicked: combobox_country.value = text }
                MenuItem { text: "BD - Bangladesh"; onClicked: combobox_country.value = text }
                MenuItem { text: "BB - Barbados"; onClicked: combobox_country.value = text }
                MenuItem { text: "BY - Belarus"; onClicked: combobox_country.value = text }
                MenuItem { text: "BE - Belgium"; onClicked: combobox_country.value = text }
                MenuItem { text: "BZ - Belize"; onClicked: combobox_country.value = text }
                MenuItem { text: "BJ - Benin"; onClicked: combobox_country.value = text }
                MenuItem { text: "BM - Bermuda"; onClicked: combobox_country.value = text }
                MenuItem { text: "BT - Bhutan"; onClicked: combobox_country.value = text }
                MenuItem { text: "BO - Bolivia"; onClicked: combobox_country.value = text }
                MenuItem { text: "BQ - Bonaire Sint Eustatius and Saba"; onClicked: combobox_country.value = text }
                MenuItem { text: "BA - Bosnia and Herzegovina"; onClicked: combobox_country.value = text }
                MenuItem { text: "BW - Botswana"; onClicked: combobox_country.value = text }
                MenuItem { text: "BV - Bouvet Island"; onClicked: combobox_country.value = text }
                MenuItem { text: "BR - Brazil"; onClicked: combobox_country.value = text }
                MenuItem { text: "IO - British Indian Ocean Territory"; onClicked: combobox_country.value = text }
                MenuItem { text: "BN - Brunei Darussalam"; onClicked: combobox_country.value = text }
                MenuItem { text: "BG - Bulgaria"; onClicked: combobox_country.value = text }
                MenuItem { text: "BF - Burkina Faso"; onClicked: combobox_country.value = text }
                MenuItem { text: "BI - Burundi"; onClicked: combobox_country.value = text }
                MenuItem { text: "CV - Cabo Verde"; onClicked: combobox_country.value = text }
                MenuItem { text: "KH - Cambodia"; onClicked: combobox_country.value = text }
                MenuItem { text: "CM - Cameroon"; onClicked: combobox_country.value = text }
                MenuItem { text: "CA - Canada"; onClicked: combobox_country.value = text }
                MenuItem { text: "KY - Cayman Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "CF - Central African Republic"; onClicked: combobox_country.value = text }
                MenuItem { text: "TD - Chad"; onClicked: combobox_country.value = text }
                MenuItem { text: "CL - Chile"; onClicked: combobox_country.value = text }
                MenuItem { text: "CN - China"; onClicked: combobox_country.value = text }
                MenuItem { text: "CX - Christmas Island"; onClicked: combobox_country.value = text }
                MenuItem { text: "CC - Cocos (Keeling) Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "CO - Colombia"; onClicked: combobox_country.value = text }
                MenuItem { text: "KM - Comoros"; onClicked: combobox_country.value = text }
                MenuItem { text: "CG - Congo"; onClicked: combobox_country.value = text }
                MenuItem { text: "CD - Congo (Democratic Republic of the)"; onClicked: combobox_country.value = text }
                MenuItem { text: "CK - Cook Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "CR - Costa Rica"; onClicked: combobox_country.value = text }
                MenuItem { text: "HR - Croatia"; onClicked: combobox_country.value = text }
                MenuItem { text: "CU - Cuba"; onClicked: combobox_country.value = text }
                MenuItem { text: "CW - Curaçao"; onClicked: combobox_country.value = text }
                MenuItem { text: "CY - Cyprus"; onClicked: combobox_country.value = text }
                MenuItem { text: "CZ - Czech Republic"; onClicked: combobox_country.value = text }
                MenuItem { text: "DK - Denmark"; onClicked: combobox_country.value = text }
                MenuItem { text: "DJ - Djibouti"; onClicked: combobox_country.value = text }
                MenuItem { text: "DM - Dominica"; onClicked: combobox_country.value = text }
                MenuItem { text: "DO - Dominican Republic"; onClicked: combobox_country.value = text }
                MenuItem { text: "EC - Ecuador"; onClicked: combobox_country.value = text }
                MenuItem { text: "EG - Egypt"; onClicked: combobox_country.value = text }
                MenuItem { text: "SV - El Salvador"; onClicked: combobox_country.value = text }
                MenuItem { text: "GQ - Equatorial Guinea"; onClicked: combobox_country.value = text }
                MenuItem { text: "ER - Eritrea"; onClicked: combobox_country.value = text }
                MenuItem { text: "EE - Estonia"; onClicked: combobox_country.value = text }
                MenuItem { text: "SZ - Eswatini"; onClicked: combobox_country.value = text }
                MenuItem { text: "ET - Ethiopia"; onClicked: combobox_country.value = text }
                MenuItem { text: "FK - Falkland Islands (Malvinas)"; onClicked: combobox_country.value = text }
                MenuItem { text: "FO - Faroe Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "FJ - Fiji"; onClicked: combobox_country.value = text }
                MenuItem { text: "FI - Finland"; onClicked: combobox_country.value = text }
                MenuItem { text: "FR - France"; onClicked: combobox_country.value = text }
                MenuItem { text: "GF - French Guiana"; onClicked: combobox_country.value = text }
                MenuItem { text: "PF - French Polynesia"; onClicked: combobox_country.value = text }
                MenuItem { text: "TF - French Southern Territories"; onClicked: combobox_country.value = text }
                MenuItem { text: "GA - Gabon"; onClicked: combobox_country.value = text }
                MenuItem { text: "GM - Gambia"; onClicked: combobox_country.value = text }
                MenuItem { text: "GE - Georgia"; onClicked: combobox_country.value = text }
                MenuItem { text: "DE - Germany"; onClicked: combobox_country.value = text }
                MenuItem { text: "GH - Ghana"; onClicked: combobox_country.value = text }
                MenuItem { text: "GI - Gibraltar"; onClicked: combobox_country.value = text }
                MenuItem { text: "GR - Greece"; onClicked: combobox_country.value = text }
                MenuItem { text: "GL - Greenland"; onClicked: combobox_country.value = text }
                MenuItem { text: "GD - Grenada"; onClicked: combobox_country.value = text }
                MenuItem { text: "GP - Guadeloupe"; onClicked: combobox_country.value = text }
                MenuItem { text: "GU - Guam"; onClicked: combobox_country.value = text }
                MenuItem { text: "GT - Guatemala"; onClicked: combobox_country.value = text }
                MenuItem { text: "GG - Guernsey"; onClicked: combobox_country.value = text }
                MenuItem { text: "GN - Guinea"; onClicked: combobox_country.value = text }
                MenuItem { text: "GW - Guinea-Bissau"; onClicked: combobox_country.value = text }
                MenuItem { text: "GY - Guyana"; onClicked: combobox_country.value = text }
                MenuItem { text: "HT - Haiti"; onClicked: combobox_country.value = text }
                MenuItem { text: "HM - Heard Island and McDonald Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "VA - Holy See (Vatican City State)"; onClicked: combobox_country.value = text }
                MenuItem { text: "HN - Honduras"; onClicked: combobox_country.value = text }
                MenuItem { text: "HK - Hong Kong"; onClicked: combobox_country.value = text }
                MenuItem { text: "HU - Hungary"; onClicked: combobox_country.value = text }
                MenuItem { text: "IS - Iceland"; onClicked: combobox_country.value = text }
                MenuItem { text: "IN - India"; onClicked: combobox_country.value = text }
                MenuItem { text: "ID - Indonesia"; onClicked: combobox_country.value = text }
                MenuItem { text: "IR - Iran (Islamic Republic of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "IQ - Iraq"; onClicked: combobox_country.value = text }
                MenuItem { text: "IE - Ireland"; onClicked: combobox_country.value = text }
                MenuItem { text: "IM - Isle of Man"; onClicked: combobox_country.value = text }
                MenuItem { text: "IL - Israel"; onClicked: combobox_country.value = text }
                MenuItem { text: "IT - Italy"; onClicked: combobox_country.value = text }
                MenuItem { text: "JM - Jamaica"; onClicked: combobox_country.value = text }
                MenuItem { text: "JP - Japan"; onClicked: combobox_country.value = text }
                MenuItem { text: "JE - Jersey"; onClicked: combobox_country.value = text }
                MenuItem { text: "JO - Jordan"; onClicked: combobox_country.value = text }
                MenuItem { text: "KZ - Kazakhstan"; onClicked: combobox_country.value = text }
                MenuItem { text: "KE - Kenya"; onClicked: combobox_country.value = text }
                MenuItem { text: "KI - Kiribati"; onClicked: combobox_country.value = text }
                MenuItem { text: "KP - Korea (Democratic People's Republic of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "KR - Korea (Republic of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "KW - Kuwait"; onClicked: combobox_country.value = text }
                MenuItem { text: "KG - Kyrgyzstan"; onClicked: combobox_country.value = text }
                MenuItem { text: "LA - Lao People's Democratic Republic"; onClicked: combobox_country.value = text }
                MenuItem { text: "LV - Latvia"; onClicked: combobox_country.value = text }
                MenuItem { text: "LB - Lebanon"; onClicked: combobox_country.value = text }
                MenuItem { text: "LS - Lesotho"; onClicked: combobox_country.value = text }
                MenuItem { text: "LR - Liberia"; onClicked: combobox_country.value = text }
                MenuItem { text: "LY - Libya"; onClicked: combobox_country.value = text }
                MenuItem { text: "LI - Liechtenstein"; onClicked: combobox_country.value = text }
                MenuItem { text: "LT - Lithuania"; onClicked: combobox_country.value = text }
                MenuItem { text: "LU - Luxembourg"; onClicked: combobox_country.value = text }
                MenuItem { text: "MO - Macao"; onClicked: combobox_country.value = text }
                MenuItem { text: "MG - Madagascar"; onClicked: combobox_country.value = text }
                MenuItem { text: "MW - Malawi"; onClicked: combobox_country.value = text }
                MenuItem { text: "MY - Malaysia"; onClicked: combobox_country.value = text }
                MenuItem { text: "MV - Maldives"; onClicked: combobox_country.value = text }
                MenuItem { text: "ML - Mali"; onClicked: combobox_country.value = text }
                MenuItem { text: "MT - Malta"; onClicked: combobox_country.value = text }
                MenuItem { text: "MH - Marshall Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "MQ - Martinique"; onClicked: combobox_country.value = text }
                MenuItem { text: "MR - Mauritania"; onClicked: combobox_country.value = text }
                MenuItem { text: "MU - Mauritius"; onClicked: combobox_country.value = text }
                MenuItem { text: "YT - Mayotte"; onClicked: combobox_country.value = text }
                MenuItem { text: "MX - Mexico"; onClicked: combobox_country.value = text }
                MenuItem { text: "FM - Micronesia (Federated States of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "MD - Moldova (Republic of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "MC - Monaco"; onClicked: combobox_country.value = text }
                MenuItem { text: "MN - Mongolia"; onClicked: combobox_country.value = text }
                MenuItem { text: "ME - Montenegro"; onClicked: combobox_country.value = text }
                MenuItem { text: "MS - Montserrat"; onClicked: combobox_country.value = text }
                MenuItem { text: "MA - Morocco"; onClicked: combobox_country.value = text }
                MenuItem { text: "MZ - Mozambique"; onClicked: combobox_country.value = text }
                MenuItem { text: "MM - Myanmar"; onClicked: combobox_country.value = text }
                MenuItem { text: "NA - Namibia"; onClicked: combobox_country.value = text }
                MenuItem { text: "NR - Nauru"; onClicked: combobox_country.value = text }
                MenuItem { text: "NP - Nepal"; onClicked: combobox_country.value = text }
                MenuItem { text: "NL - Netherlands"; onClicked: combobox_country.value = text }
                MenuItem { text: "NC - New Caledonia"; onClicked: combobox_country.value = text }
                MenuItem { text: "NZ - New Zealand"; onClicked: combobox_country.value = text }
                MenuItem { text: "NI - Nicaragua"; onClicked: combobox_country.value = text }
                MenuItem { text: "NE - Niger"; onClicked: combobox_country.value = text }
                MenuItem { text: "NG - Nigeria"; onClicked: combobox_country.value = text }
                MenuItem { text: "NU - Niue"; onClicked: combobox_country.value = text }
                MenuItem { text: "NF - Norfolk Island"; onClicked: combobox_country.value = text }
                MenuItem { text: "MK - North Macedonia"; onClicked: combobox_country.value = text }
                MenuItem { text: "MP - Northern Mariana Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "NO - Norway"; onClicked: combobox_country.value = text }
                MenuItem { text: "OM - Oman"; onClicked: combobox_country.value = text }
                MenuItem { text: "PK - Pakistan"; onClicked: combobox_country.value = text }
                MenuItem { text: "PW - Palau"; onClicked: combobox_country.value = text }
                MenuItem { text: "PS - Palestine State of"; onClicked: combobox_country.value = text }
                MenuItem { text: "PA - Panama"; onClicked: combobox_country.value = text }
                MenuItem { text: "PG - Papua New Guinea"; onClicked: combobox_country.value = text }
                MenuItem { text: "PY - Paraguay"; onClicked: combobox_country.value = text }
                MenuItem { text: "PE - Peru"; onClicked: combobox_country.value = text }
                MenuItem { text: "PH - Philippines"; onClicked: combobox_country.value = text }
                MenuItem { text: "PN - Pitcairn"; onClicked: combobox_country.value = text }
                MenuItem { text: "PL - Poland"; onClicked: combobox_country.value = text }
                MenuItem { text: "PT - Portugal"; onClicked: combobox_country.value = text }
                MenuItem { text: "PR - Puerto Rico"; onClicked: combobox_country.value = text }
                MenuItem { text: "QA - Qatar"; onClicked: combobox_country.value = text }
                MenuItem { text: "RE - Réunion"; onClicked: combobox_country.value = text }
                MenuItem { text: "RO - Romania"; onClicked: combobox_country.value = text }
                MenuItem { text: "RU - Russian Federation"; onClicked: combobox_country.value = text }
                MenuItem { text: "RW - Rwanda"; onClicked: combobox_country.value = text }
                MenuItem { text: "BL - Saint Barthélemy"; onClicked: combobox_country.value = text }
                MenuItem { text: "SH - Saint Helena Ascension and Tristan da Cunha"; onClicked: combobox_country.value = text }
                MenuItem { text: "KN - Saint Kitts and Nevis"; onClicked: combobox_country.value = text }
                MenuItem { text: "LC - Saint Lucia"; onClicked: combobox_country.value = text }
                MenuItem { text: "MF - Saint Martin (French part)"; onClicked: combobox_country.value = text }
                MenuItem { text: "PM - Saint Pierre and Miquelon"; onClicked: combobox_country.value = text }
                MenuItem { text: "VC - Saint Vincent and the Grenadines"; onClicked: combobox_country.value = text }
                MenuItem { text: "WS - Samoa"; onClicked: combobox_country.value = text }
                MenuItem { text: "SM - San Marino"; onClicked: combobox_country.value = text }
                MenuItem { text: "ST - Sao Tome and Principe"; onClicked: combobox_country.value = text }
                MenuItem { text: "SA - Saudi Arabia"; onClicked: combobox_country.value = text }
                MenuItem { text: "SN - Senegal"; onClicked: combobox_country.value = text }
                MenuItem { text: "RS - Serbia"; onClicked: combobox_country.value = text }
                MenuItem { text: "SC - Seychelles"; onClicked: combobox_country.value = text }
                MenuItem { text: "SL - Sierra Leone"; onClicked: combobox_country.value = text }
                MenuItem { text: "SG - Singapore"; onClicked: combobox_country.value = text }
                MenuItem { text: "SX - Sint Maarten (Dutch part)"; onClicked: combobox_country.value = text }
                MenuItem { text: "SK - Slovakia"; onClicked: combobox_country.value = text }
                MenuItem { text: "SI - Slovenia"; onClicked: combobox_country.value = text }
                MenuItem { text: "SB - Solomon Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "SO - Somalia"; onClicked: combobox_country.value = text }
                MenuItem { text: "ZA - South Africa"; onClicked: combobox_country.value = text }
                MenuItem { text: "GS - South Georgia and the South Sandwich Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "SS - South Sudan"; onClicked: combobox_country.value = text }
                MenuItem { text: "ES - Spain"; onClicked: combobox_country.value = text }
                MenuItem { text: "LK - Sri Lanka"; onClicked: combobox_country.value = text }
                MenuItem { text: "SD - Sudan"; onClicked: combobox_country.value = text }
                MenuItem { text: "SR - Suriname"; onClicked: combobox_country.value = text }
                MenuItem { text: "SJ - Svalbard and Jan Mayen"; onClicked: combobox_country.value = text }
                MenuItem { text: "SE - Sweden"; onClicked: combobox_country.value = text }
                MenuItem { text: "CH - Switzerland"; onClicked: combobox_country.value = text }
                MenuItem { text: "SY - Syrian Arab Republic"; onClicked: combobox_country.value = text }
                MenuItem { text: "TW - Taiwan Province of China"; onClicked: combobox_country.value = text }
                MenuItem { text: "TJ - Tajikistan"; onClicked: combobox_country.value = text }
                MenuItem { text: "TZ - Tanzania United Republic of"; onClicked: combobox_country.value = text }
                MenuItem { text: "TH - Thailand"; onClicked: combobox_country.value = text }
                MenuItem { text: "TL - Timor-Leste"; onClicked: combobox_country.value = text }
                MenuItem { text: "TG - Togo"; onClicked: combobox_country.value = text }
                MenuItem { text: "TK - Tokelau"; onClicked: combobox_country.value = text }
                MenuItem { text: "TO - Tonga"; onClicked: combobox_country.value = text }
                MenuItem { text: "TT - Trinidad and Tobago"; onClicked: combobox_country.value = text }
                MenuItem { text: "TN - Tunisia"; onClicked: combobox_country.value = text }
                MenuItem { text: "TR - Turkey"; onClicked: combobox_country.value = text }
                MenuItem { text: "TM - Turkmenistan"; onClicked: combobox_country.value = text }
                MenuItem { text: "TC - Turks and Caicos Islands"; onClicked: combobox_country.value = text }
                MenuItem { text: "TV - Tuvalu"; onClicked: combobox_country.value = text }
                MenuItem { text: "UG - Uganda"; onClicked: combobox_country.value = text }
                MenuItem { text: "UA - Ukraine"; onClicked: combobox_country.value = text }
                MenuItem { text: "AE - United Arab Emirates"; onClicked: combobox_country.value = text }
                MenuItem { text: "GB - United Kingdom of Great Britain and Northern Ireland"; onClicked: combobox_country.value = text }
                MenuItem { text: "US - United States of America"; onClicked: combobox_country.value = text }
                MenuItem { text: "UY - Uruguay"; onClicked: combobox_country.value = text }
                MenuItem { text: "UZ - Uzbekistan"; onClicked: combobox_country.value = text }
                MenuItem { text: "VU - Vanuatu"; onClicked: combobox_country.value = text }
                MenuItem { text: "VE - Venezuela (Bolivarian Republic of)"; onClicked: combobox_country.value = text }
                MenuItem { text: "VN - Viet Nam"; onClicked: combobox_country.value = text }
                MenuItem { text: "WF - Wallis and Futuna"; onClicked: combobox_country.value = text }
                MenuItem { text: "EH - Western Sahara"; onClicked: combobox_country.value = text }
                MenuItem { text: "YE - Yemen"; onClicked: combobox_country.value = text }
                MenuItem { text: "ZM - Zambia"; onClicked: combobox_country.value = text }
                MenuItem { text: "ZW - Zimbabwe"; onClicked: combobox_country.value = text }
            }
            anchors.horizontalCenter: lbl.horizontalCenter
        }

    }
}
